pipeline {
    agent any
    stages {
        stage('build with unit test, package and store the jar') {
            steps {
            	echo 'Building app...'
                sh 'mvn -U -f Store-management-system clean install -Dintegration-tests.skip=true'
            }
        }
        
        stage('deploy app') {
            steps {
            	echo 'Deploying app...'            	
				sh 'ls -l Store-management-system/foco-store-integration/target/classes/foco-store-server-0.0.1-SNAPSHOT.jar'
                sh 'nohup java -jar Store-management-system/foco-store-integration/target/classes/*.jar &'			                               
            }
        }
        
        stage('run integration tests') {
            steps {
            	echo 'Running integration tests...'
            	sh 'mvn -f Store-management-system -Pintegration clean verify -DskipUTs'
            }
        }
    }
}
